### ISSUE TITLE
assertive dependency is not available anymore

### ISSUE THREAD

**Issue by fmannhardt** [bupaverse/bpmnR#3]
Trying to install the package via `remotes` does not work since the dependency `assertive` seems to have been removed/renamed.

**Comment by fmannhardt** [comment]
It seems to be available from Bitbucket (https://bitbucket.org/richierocks/assertive/src/master/) but installing via `remotes::install_bitbucket("richierocks/assertive")` also fails with all downstream dependencies not being installed.

The issue of CRAN removal is tracked here:
https://bitbucket.org/richierocks/assertive/issues/29/cran-assertive-maintainer
with a workaround. These CRAN policies really start to get annoying for keeping stuff running. Maybe we can simply not rely on `assertive`?

**Comment by gertjanssenswillen** [comment]
I don't think assertive is necessary, I'll be removing it
